### ISSUE TITLE
Add prefix to x-unit in plots

### ISSUE THREAD

**Issue by Rastamo** [johannes-wolf/typst-canvas#130]
I think there are use cases where prefix is needed as well. For example, week 1, week 2 etc.

**Comment by johannes-wolf** [comment]
This is already possible by supplying your own tick formatting function:
`x-format: v => [Week #v]`

But I will add options for proper rotation etc. :+1:

**Comment by Rastamo** [comment]
That is even better. Just learning the library. Thanks!
Yeah, rotations is needed for longer tick labels. 👍

**Comment by johannes-wolf** [comment]
Rotation got implemented via #135.
