### ISSUE TITLE
Customize axis tick direction

### ISSUE THREAD

**Issue by tmbb** [johannes-wolf/typst-canvas#131]
Currently, it seems like one can't customize the direction (inner vs outer) of the axis ticks. For example, I'd like to copy the NEJM styles for kaplan-meier curves:

![image](https://github.com/johannes-wolf/typst-canvas/assets/2668874/6048e10a-78f0-467f-b56b-0cf4f2f5304d)

But I can't find a way to make the ticks point the right way.

**Comment by johannes-wolf** [comment]
I have fixed this. With the current `master` you can set a negative tick length for "scientific" and "left" style plots.
