### ISSUE TITLE
Custom style roots

### ISSUE THREAD

**Issue by jneug** [johannes-wolf/typst-canvas#133]
Package authors will want to provide custom style roots to allow styling their custom elements. 

For example, I am working ob a package to draw finite automata and would like to add the roots `state` and `transition`, to allow global styling of these elements.

These additions might be useful in this context:
- Add a `load-defaults` function to load a dictionary of default styles into the context. 
- Add an optional `default-styles` key to element dictionaries, that loads the returned default styles into the context if the returned style root do not exist yet. This would allow package authors to provide a default style with their custom elements.
- Add a `default-style` argument to `canvas`, to allow package authors to pass in default styles, when wrapping `canvas` inside their own functions.

**Comment by jneug** [comment]
I just realized, that elements already support a `style` and `before` key. 

Those already should allow users to add custom styles to the context, shouldn't they?

**Comment by johannes-wolf** [comment]
Yes, both callbacks allow for modifying the context's style.

**Comment by jneug** [comment]
I guess this can be closed then. 

Is there any specific reason, why the `style` callback existed? It seems manipulating the styles could be done via `before` as well. 

Maybe for semantic reasons a `default-styles` callback could still be useful.

**Comment by johannes-wolf** [comment]
> 

That should work. In `lib/axes.typ` I merge a local defaut-style dictionary with the result of `styles.resolve(..)` to be able to have custom style roots without polluting the global style.

**Comment by johannes-wolf** [comment]
Yes, should be the same.

**Comment by jneug** [comment]
Thanks for the clarifications. 

I think I'm ready to publish my package soon. Needs some polish and proper documentation, but the drawing part works at least. 

You can have a look at it here: https://github.com/jneug/typst-finite

**Comment by johannes-wolf** [comment]
Look very nice! :)

**Comment by johannes-wolf** [comment]
Should we create a follow up ticket for implementing said functionality (passing root styles into canvas calls) or can this be closed?

**Comment by jneug** [comment]
I think this can be closed, since there are already multiple ways of solving this problem. 

Maybe a kind of best practice could be mentioned in the developer docs.

**Comment by johannes-wolf** [comment]
Thank you. I will create a ticket.
