### ISSUE TITLE
proposal: Shorter syntax for arrows and lines with labels

### ISSUE THREAD

**Issue by johannes-wolf** [johannes-wolf/typst-canvas#144]
I often draw arrows and/or lines with labels attached to them, therefore I propose to add a
"faster" syntax for drawing lines with marks and labels.

One option would be to allow positional content in the `line` function:
```
line((0,0), [My Text], (1,0))
```

The positioning could be controlled via additional style attributes.
Arrows could be entered by allowing string arguments of a certain format to place arrowheads along the path.

```
line("<-", (0,0), [My Text], (1,0) "-|")
```

An alternative would be to have a special function for all of this. Maybe `arrow`? I can not come up with a good name though. @fenjalien 

Maybe something like a more "magic" `path` function which supports multiple primitives via a
short syntax?
```
path((0,0), [My Text], (1,0), ("~", (2,0), (2,1)), (rel: (0, 1), "->")
     ^---- straigh line ---^  ^--- bezier   ----^  ^- line   -^  ^--- arrow head at the end
```

**Comment by fenjalien** [comment]
So ATM you have to do:
```
line((0,0), (1,0), name: "l")
content("l.mid")[Text]
```
I feel like what you've proposed is dangerously close to tikz's path syntax but even more confusing as we won't have syntax of when not to draw a line.

For a path function though I would want it to be similar to an SVG path. So M for `move-pt`, L for `line` etc. we could include anchor definitions as well.

**Comment by johannes-wolf** [comment]
ATM you have to do
```
line((0,0), (1,0), name: "l", mark: (start: ">", end: ">"))
content((rel: (0, .1), to: "l.mid"), [Text], anchor: "bottom") // Place text above a line
```
which is a lot of boiler-plate. Rotating text with the line gets even more verbose.

Maybe `path` is a bad name. But some shortcuts with a simpler+faster syntax would be really nice.

**Comment by fenjalien** [comment]
While I agree having shorter way to write that would be nice, I don't really want to commit to this being "standard" (or part of the "core" library) I guess. I wouldn't mind it being part of a lib as it would make it easier to safely depreceate later on if we want to. Just a thought on adding more libs though, it might make reworking the backend api a bit more difficult but still not impossible.

**Comment by johannes-wolf** [comment]
With the current implementation `auto` only inherits form the very "bottom" though.
