### ISSUE TITLE
Major rendering errors in firefox

### ISSUE THREAD

**Issue by freundTech** [johannes-wolf/typst-canvas#163]
Opening the manual pdf in firefox (both in the github preview and in the firefox pdf viewer) many charts, especially charts with curved lines, have major rendering errors.

Here is a screenshot of page 37 of the manual pdf in firefox:
![Screenshot from 2023-09-09 17-20-56](https://github.com/johannes-wolf/typst-canvas/assets/9515067/e0f6b4c7-ce9c-4447-b4e4-fdaeb1526223)
And here the same page in gnome document viewer, rendering fine:
![Screenshot from 2023-09-09 17-21-08](https://github.com/johannes-wolf/typst-canvas/assets/9515067/5e83e075-d348-4f7b-8db7-02a1f5f4b130)

**Comment by fenjalien** [comment]
This is a known issue with firefox's PDF viewer. Unfortunately there's nothing we can do about it here :(

https://github.com/mozilla/pdf.js/issues/16619
https://github.com/typst/typst/issues/1611

**Comment by fenjalien** [comment]
oops it actually looks like it might be fixed in Firefox version 119? https://bugzilla.mozilla.org/show_bug.cgi?id=1841020
