### ISSUE TITLE
Divide by zero inside cetz

### ISSUE THREAD

**Issue by raphCode** [johannes-wolf/typst-canvas#169]
The following minimal code fails inside cetz with `cannot divide by zero`:
```typst
#import"@preview/cetz:0.1.0"

#cetz.canvas({
  import cetz.draw: *
  
  scale(0.2)
  set-origin((0, -1.5))
  let r = 2
  arc((r, 0), start: 0deg, stop: -180deg, radius: r)
})
```

The error seems specific to the combination of the `arc` function, its arguments and the applied transformations. Changing anything makes the drawing work.

**Comment by johannes-wolf** [comment]
This has been fixed with release `0.1.1`.
