### ISSUE TITLE
Angle parameter of content does not resolve coordinates

### ISSUE THREAD

**Issue by raphCode** [johannes-wolf/typst-canvas#170]
The following code errors with `assertion failed`:
``` typst
#import"@preview/cetz:0.1.1"

#cetz.canvas(length:1cm, {
  import cetz.draw: *

  circle((1, 1), name: "c")
  content((0, 0), [hi], angle: "c")
})
```

I would have expected that `"c"` is internally resolved to the correct coordinates of `(1, 1)`.

**Comment by johannes-wolf** [comment]
Thank you for reporting this, this is a bug.

**Comment by fenjalien** [comment]
It is because it validates the angle to be an `angle` type or an `array` before validating the coordinate itself...

As a workaround I would recommend using the function coordinate and use a function that just returns its input, `(x => x, "c")`
