### ISSUE TITLE
Is it possible to draw smooth line graphs?

### ISSUE THREAD

**Issue by andrewragy** [johannes-wolf/typst-canvas#188]
Is it possible to provide the plot.add function with points and have it join them with a smooth curve rather than broken lines?

**Comment by andrewragy** [comment]
This is similar to [plotst](https://github.com/typst/packages/tree/main/packages/preview/plotst/0.1.0)'s rounding parameter

**Comment by johannes-wolf** [comment]
No, this is currently not possible. The plot of CeTZ is clipping the path (something that plotst does not) and therefore smoothing would require clipping bezier curves in a rect which is currently not implemented.

I do not think I will work on this in the near future by myself but I would welcome PRs.

**Comment by johannes-wolf** [comment]
Ok… this got added with PR #190. It allows calculating a Catmull-Rom and sampling it to draw smoothed data. This might be less performant because it uses sampling of the curve so the number of data points get get very big. This should get improved at a later point.

**Comment by andrewragy** [comment]
Thank you!
