### ISSUE TITLE
Bezier curve doesn't use the new path system

### ISSUE THREAD

**Issue by SekoiaTree** [johannes-wolf/typst-canvas#19]
Using the existing method means you won't need to use samples anymore, it'll be handled by typst (which I believe uses effectively-infinite precision?).

**Comment by johannes-wolf** [comment]
Yes, planning on using `path` for bezier. But path merging has to be tweaked to work correctly.
Doing it with lines is easier because we need the sample anyway for calculating the bounding box.

**Comment by johannes-wolf** [comment]
Plan is to wait for a new/better path implementation in typst as the current one lacks move operations.
