### ISSUE TITLE
Rect anchor bottom uses the top anchor

### ISSUE THREAD

**Issue by N3xed** [johannes-wolf/typst-canvas#195]
I have the following code

```typst
#canvas({
    import canvas-draw: *
    content((0, 0), block(stroke: 0.15mm+black, inset: 1.7mm, radius: 2mm, [Komponenten]), name: "tm")
    content((rel: (0, -1mm), to: "tm.bottom"), block(stroke: 0.15mm+black, inset: 1.7mm, radius: 2mm, [
        Packages\
        #sym.bullet Functions\
        #sym.bullet Procedures\
        #sym.bullet Declarations
        ]), anchor: "top", name: "bm")
    rect((rel: (-1mm, 1mm), to: "tm.top-left"), (rel: (1mm, -1mm), to: "bm.bottom-right"), stroke: black+0.2mm, name: "box")
    content((rel: (0, 0.9mm), to: "box.top"), [_Library_], anchor: "bottom")
})
```

and this somehow produces: 
![image](https://github.com/johannes-wolf/typst-canvas/assets/11508388/e9f30a4d-e81a-48da-8a05-8a3d6c146656)
where `Library` is positioned at the bottom anchor of `box` instead of the top anchor as specified.

But if I change `box.top` in the second to last line to `box.bottom`:
```typst
    content((rel: (0, 0.9mm), to: "box.bottom"), [_Library_], anchor: "bottom")
```
`Library` is positioned at the top anchor:
![image](https://github.com/johannes-wolf/typst-canvas/assets/11508388/fe032fd1-9163-4474-8210-df506b1e646f)

The first codeblock worked in a previous version, but with the latest version the anchors are somehow switched.
It uses the correct anchor if `box` is positioned using absolute coordinates.

**Comment by johannes-wolf** [comment]
This is a bug. You can swap your `rect(..)`'s two coordinates as a workaround.
I will soon add rounded rect support, which will also fix this bug :).

**Comment by N3xed** [comment]
Ohh, haven't considered this. Thanks for the quick reply.
