### ISSUE TITLE
General improvements to relative positions

### ISSUE THREAD

**Issue by PgBiel** [johannes-wolf/typst-canvas#32]
Hello,

First of all, I can't thank you enough for your effort in this project.
I'm making this issue because I have some ideas I want to share -- and would be very happy to contribute with -- regarding relative positions. Please tell me what you think!

For this particular issue, I wanted to talk about mostly three things:
1. Relative positions should be able to be applied on any valid coordinate, not just on the last one. I had done this specifically for node coordinates on a PR I had made here, but I closed it because I think this should be more general. What about some syntax like `(rel: (x, y), from: (... any valid coordinate ...))`?
It would recursively resolve that coordinate, and then apply the offsets in the coords.<br/>
    Of course, we have to keep in mind that Typst's recursion limit is 64, so, while I don't ever expect a reasonable use-case to reach that, we can easily guard against this by simply checking if the "from" coordinate is also a rel: from:, in which case we simply sum the offsets and extract the inner "from:" (and keep doing that as long as it is possible), thus avoiding more than one recursive call to coordinate resolution.

2. In order to make things easier for the end-user and avoid usage of that syntax recursively, I think we should accept multiple sum components for `rel:`. Something like `rel: ((1, 2), (3, 4), (5, 6), ...)`, and it would just sum all offsets. Going beyond, maybe we could even take arbitrary coordinates in that array, although that's not strictly necessary.

3. I think `rel:` should perhaps also accept an `(angle, distance)` array, so that we can get a coordinate relative to another by a certain angle and distance. This would also be useful in the above suggestion, where we would be able to "sum" multiple angles in an array (applying them one after the other).

Thanks for reading!

**Comment by johannes-wolf** [comment]
Sounds pretty good. Technically one can already achieve all of those cases by using a lambda as position, but I think the library should support the syntax you suggested. :)

**Comment by PgBiel** [comment]
> Thank you. Sounds pretty good. Technically one can already achieve all of those cases by using a lambda as position, but I think the library should support the syntax you suggested. :)

Nice! I think it would be cool too :)

By the way, I really didn't find out about the lambda thing until I took a peek at the code earlier... might be a good idea to add it to the manual eventually haha
But still, I think this notation might be more concise for most use-cases :+1:

**Comment by fenjalien** [comment]
These sound like some great ideas! but could you give an example of how the second format (`rel: ((1, 2), (3, 4), (5, 6), ...)`) could be used? I'm confused on how it can be used.

Ideally I would like to aim for equivalent coordinate features with Tikz: https://tikz.dev/tikz-coordinates.

**Comment by PgBiel** [comment]
> These sound like some great ideas! but could you give an example of how the second format (`rel: ((1, 2), (3, 4), (5, 6), ...)`) could be used? I'm confused on how it can be used.

The idea is for it to be like `+(...)` in TikZ (summing coordinates). It'd work not just with `(x, y)`, but also with `(angle, distance)`, and maybe any valid coordinate specification, really.

**Comment by fenjalien** [comment]
Ok so having an array of coordinates causes them to be added together once resolved. I would suggest having both implicit and explicit syntax for it would be best?

**Comment by fenjalien** [comment]
With #41, you can now use any coordinate with the `to` parameter to set what you want it to be relative to. This resolves the first and third thing.

**Comment by johannes-wolf** [comment]
Closing this, as most of these things got implemented.
