### ISSUE TITLE
Is there something like transforms or ellipses?

### ISSUE THREAD

**Issue by Kreijstal** [johannes-wolf/typst-canvas#35]
I didn't see anything in the manual regarding position or rotation transforms

**Comment by johannes-wolf** [comment]
Hi, there is `translate(<coordinates>)`, `scale(<axis-factors>)` and `rotate(<axis-angles>|<z-agle>)`, see `draw.typ`.

For other usage examples see: [demo/transform.typ](https://github.com/johannes-wolf/typst-canvas/blob/master/demo/transform.typ)
