### ISSUE TITLE
Change `node` into a group command.

### ISSUE THREAD

**Issue by fenjalien** [johannes-wolf/typst-canvas#4]
The draw command `node` currently groups together all other draw commands in its body, only records the anchors of the latest draw command by type, and allows for scoped transformations. 
In my eyes this would be better represented as a group command. With #3 a group could be optionally named if anchors to it are required.

**Comment by johannes-wolf** [comment]
I have changed the name to `group` and also removed the anchor related code of it.
The possibility of defining anchors from insides a group should be reimplemented though.
