### ISSUE TITLE
Slightly confusing errors on various invalid coordinates

### ISSUE THREAD

**Issue by MultisampledNight** [johannes-wolf/typst-canvas#42]
Before I start, this is _totally awesome_! It feels like I could build anything I want with it. Of course it's not as far as tikz in its engineering, but even its current state of things is more than I could ask for in such a new system as typst.

Then, when specifying coordinates in a few funny ways which might even be unintentional, the errors are not quite clear on what the user has done wrong. I believe most of these just require additional `assert`s before the main function body. Ideally there would be a way for typst-canvas to emit proper errors like the ones by typst itself, but I suppose that's not possible today.

## Relative with no previous coordinate

Slightly related to #32. Only seems to apply to `circle`, `arc` and `rect`. `line`, `bezier` and `content` are unimpressed, the first two draw nothing, the last one seems to just render the text at `(0, 0)`, overlaying previously drawn text in that canvas, if any.

### MVCE

```typst
#import "typst-canvas/canvas.typ": canvas
#canvas({
  import "typst-canvas/draw.typ": *
  circle(())
})
```

```
error: not enough elements to destructure
    ┌─ typst-canvas/draw.typ:224:17
    │
224 │       let (x, y, z) = center
    │                  ^
[... the call stack ...]
```

### Suggestion

Explicitly panic or use `(0, 0)` everywhere if there's no previous relative coordinate.

## `line` + no second coordinate + `mark-end` = fire

Only happens in this specific combination. `mark-start` is fine, for example.

### MVCE

```typst
#import "typst-canvas/canvas.typ": canvas
something
#canvas({
  import "typst-canvas/draw.typ": *
  line((0, 0), mark-end: ">")
})
```

```
error: array index out of bounds (index: -2, len: 1)
    ┌─ typst-canvas/draw.typ:164:28
    │
164 │         let (start, end) = (pts.pos().at(-2), pts.pos().at(-1))
    │                             ^^^^^^^^^^^^^^^^
[... the call stack ...]
```

### Suggestion

`line` should `assert` or directly somehow require in the function parameters (like for `rect`) that a second coordinate is given.

### MVCE

```typst
#import "typst-canvas/canvas.typ": canvas
something
#canvas({
  import "typst-canvas/draw.typ": *
  rect((0, 0), (), name: "hmm yes a rect")
  line("nonexistent node", "anywhere")
})
```

```
error: assertion failed: Unknown node 'nonexistent node' in nodes (
  "hmm yes a rect": (
    center: (0.0, 0.0, 0),
    left: (0.0, 0.0, 0),
    right: (0.0, 0.0, 0),
    top: (0.0, 0.0, 0),
    bottom: (0.0, 0.0, 0),
    top-left: (0.0, 0.0, 0),
    top-right: (0.0, 0.0, 0),
    bottom-left: (0.0, 0.0, 0),
    bottom-right: (0.0, 0.0, 0),
    above: (0.0, 0.0, 0),
    below: (0.0, 0.0, 0),
  ),
)
   ┌─ typst-canvas/util.typ:46:12
   │
46 │         assert(c.node in ctx.anchors,
   │ ╭─────────────^
47 │ │              message: "Unknown node '" + c.node + "' in nodes " + repr(ctx.anchors))
   │ ╰────────────────────────────────────────────────────────────────────────────────────^
[... the call stack ...]
```

### Suggestion

_Ideally_ it would state that the node requested is not specified, and list similar ones based on the closest ones according to the [Levenshtein distance](https://en.wikipedia.org/wiki/Levenshtein_distance). But a bare "not found, these are the ones I have" with _only_ the node names would be fine, too.

**Comment by fenjalien** [comment]
Hi, thanks for the feedback! I'm currently over-hauling the coordinate system in #41 and have already addressed your first and last issue. The second issue shouldn't be too hard to fix...
