### ISSUE TITLE
Allow setting anchors in the root scope

### ISSUE THREAD

**Issue by johannes-wolf** [johannes-wolf/typst-canvas#47]
Allow setting anchors without using a group.
```
#canvas({
  anchor("A", (1,1))
  ...
})
```

Current solution is to use a named group:
```
#canvas({
  group(name: "nodes", {
    anchor("A", (1,1))
  })
})
```

**Comment by jdbosser** [comment]
Is this feature released yet? I tried to create an anchor in the root, and cetz yells at me that it found an anchor outside of a group.

**Comment by johannes-wolf** [comment]
No, this is not implemented. Should I re-open the issue?

**Comment by jdbosser** [comment]
I think so, if the feature is still planned. If you have decided that this is no longer on the roadmap, then I think it should be left closed.
