### ISSUE TITLE
Relative position without setting the new position

### ISSUE THREAD

**Issue by fenjalien** [johannes-wolf/typst-canvas#5]
Currently `(0,1)` specifies an absolute position and `(rel: (0,1))` specifies a position relative to the previous position and then sets that as the new previous position. The equivalent syntax in [Tikz](https://tikz.dev/) is the same for absolute positions, `++(0,1)` is for a relative position and sets the new previous position, but `+(0,1)` specifies a position relative to the previous position and then does not set a new previous position.

Some ideas for the syntax:
- `(rel: (0,1), modify: false)`
- `("+": (0,1))`

**Comment by johannes-wolf** [comment]
Would prefer the first (modify: false) version.

**Comment by johannes-wolf** [comment]
For `rel` I have implemented `move: <bool>`.

**Comment by fenjalien** [comment]
#41
