### ISSUE TITLE
How to do fillings?

### ISSUE THREAD

**Issue by Kreijstal** [johannes-wolf/typst-canvas#50]
Not circles, or squares but filled shapes. That could for example be described by bezier curves?

**Comment by fenjalien** [comment]
You can fill shapes using `fill` and passing it a color (https://typst.app/docs/reference/types/color/)

Here are some examples:
```typ
fill(red)
line((0,0), (1,1), (2, 0), close: true)
```
![image](https://github.com/johannes-wolf/typst-canvas/assets/34489450/b5c3eae5-6627-4ea8-9d11-f19071a592e9)
```typ
fill(red)
bezier((0, 0), (2, 0), (1, 1))
bezier((0, -1), (2, -1), (.5, -2), (1.5, 0))
```
![image](https://github.com/johannes-wolf/typst-canvas/assets/34489450/74ca779b-fe45-4360-a059-b2bfc4d0a755)

**Comment by johannes-wolf** [comment]
Filling shapes made out of multiple bezier curves is currently not possible, as `merge-path` does not support that. This is a todo.
