### ISSUE TITLE
Generalised Styling Method

### ISSUE THREAD

**Issue by fenjalien** [johannes-wolf/typst-canvas#57]
When styling in Ti*kZ* you use key-value pairs which can be passed to draw commands using square brackets or with the `\tikzset` command. In typst-canvas you set the stroke and fill with the dedicated methods or for each draw command, additional styling for elements can be set with their respective draw functions.

I want to propose a new function that can set styling options for all elements in a similar manner to Ti*kZ*'s key-value pairs except with dictionaries (as this is Typst's equivalent). The current `stroke` and `fill` methods can remain as short hand notation for this generalised method.

### Name
Either `style` or `styling`, with a possible prefix of `set-`.

### How it should work / Ideas
```
#set-style(..styling)
```
To set the stroke and fill of following draw methods:
```
// Stroke of blue and fill of red
set-style(stroke: blue, fill: red)
// Draws a red circle with a blue border
circle(())
```

Dictionaries should update the style, not override the option:
```
// Red stroke with a thickness of 5pt
set-style(stroke: (paint: red, thickness: 5pt))
// Changes the stroke to be blue but keeps the thickness of 5pt
set-style(stroke: (paint: blue))
```
A way to specify that the dictionary should set the value instead of updating it should be made available. Maybe `update: false` to keep a similar syntax to relative coordinates.

It should be possible to override and set styling for each draw method:
```
// Sets the global stroke to red
set-style(stroke: red)
// Sets the stroke for this line to be blue
line((1,0), (0,0), stroke: blue)
```
This could be done by using a `styling` sink argument for named parameters.

It could be possible to set specific styling for each type element:
```
// Sets the stroke of lines to be red and the stroke of circles to be blue. 
// All other elements have the default style.
set-style(
  line: (stroke: red),
  circle: (stroke: blue)
)
```

You should be able to for the styling of arrow heads on lines:
```
set-style(line: (mark: (begin: ">")))
line((0,0), (0,1))
// The above is equivalent to 
line((0,0), (0,1), mark-begin: ">")
```

A short hand for single values in nested dictionaries should also be possible:
```
set-style("line.mark.begin": ">")
```

---

**Comment by SimonYde** [comment]
Is set-style intended to work for bezier curves? I cannot get the following to work:

```typst
set-style(
  bezier: (stroke: (dash: "dashed"))
)
```

It only works when doing the following:
```typst
set-style(
  stroke: (dash: "dashed")
)
```

**Comment by johannes-wolf** [comment]
> Is set-style intended to work for bezier curves? I cannot get the following to work:
> 
> ```typst
> set-style(
>   bezier: (stroke: (dash: "dashed"))
> )
> ```
> 
> It only works when doing the following:
> 
> ```typst
> set-style(
>   stroke: (dash: "dashed")
> )
> ```

The following works fine for me:
```
set-style(bezier: (stroke: (dash: "dashed")))
bezier((0,0), (5,0), (1,2), (4,-2))
```

Can you give a more detailed example where it does not?
Did you call `set-style` before in the canvas?

**Comment by SimonYde** [comment]
> > Is set-style intended to work for bezier curves? I cannot get the following to work:
> > ```typst
> > set-style(
> >   bezier: (stroke: (dash: "dashed"))
> > )
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > It only works when doing the following:
> > ```typst
> > set-style(
> >   stroke: (dash: "dashed")
> > )
> > ```
> 
> The following works fine for me:
> 
> ```
> set-style(bezier: (stroke: (dash: "dashed")))
> bezier((0,0), (5,0), (1,2), (4,-2))
> ```
> 
> Can you give a more detailed example where it does not? Did you call `set-style` before in the canvas?

It would appear to not work in cases like the following:

```typst
#cetz.canvas({
    import cetz.draw: *
    set-style(bezier: (stroke: (dash: "dashed", thickness: 1pt)))
    merge-path({
      bezier((1.5, -5), (3.5, -6), (1.5, -6.5))
      bezier((7, -5), (9, -6), (9, -4.5))
    })
})
```
Neither does it work for:
```typst
#cetz.canvas({
    import cetz.draw: *
    merge-path({
      set-style(bezier: (stroke: (dash: "dashed", thickness: 1pt)))
      bezier((1.5, -5), (3.5, -6), (1.5, -6.5))
      bezier((7, -5), (9, -6), (9, -4.5))
    })
})
```
It would appear that `set-style` does not apply for `merge-path` constructions.

**Comment by SimonYde** [comment]
> > > Is set-style intended to work for bezier curves? I cannot get the following to work:
> > > ```typst
> > > set-style(
> > >   bezier: (stroke: (dash: "dashed"))
> > > )
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > It only works when doing the following:
> > > ```typst
> > > set-style(
> > >   stroke: (dash: "dashed")
> > > )
> > > ```
> > 
> > 
> > The following works fine for me:
> > ```
> > set-style(bezier: (stroke: (dash: "dashed")))
> > bezier((0,0), (5,0), (1,2), (4,-2))
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Can you give a more detailed example where it does not? Did you call `set-style` before in the canvas?
> 
> It would appear to not work in cases like the following:
> 
> ```typst
> #cetz.canvas({
>     import cetz.draw: *
>     set-style(bezier: (stroke: (dash: "dashed", thickness: 1pt)))
>     merge-path({
>       bezier((1.5, -5), (3.5, -6), (1.5, -6.5))
>       bezier((7, -5), (9, -6), (9, -4.5))
>     })
> })
> ```
> 
> Neither does it work for:
> 
> ```typst
> #cetz.canvas({
>     import cetz.draw: *
>     merge-path({
>       set-style(bezier: (stroke: (dash: "dashed", thickness: 1pt)))
>       bezier((1.5, -5), (3.5, -6), (1.5, -6.5))
>       bezier((7, -5), (9, -6), (9, -4.5))
>     })
> })
> ```
> 
> It would appear that `set-style` does not apply for `merge-path` constructions.



> > Is set-style intended to work for bezier curves? I cannot get the following to work:
> > ```typst
> > set-style(
> >   bezier: (stroke: (dash: "dashed"))
> > )
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > It only works when doing the following:
> > ```typst
> > set-style(
> >   stroke: (dash: "dashed")
> > )
> > ```
> 
> The following works fine for me:
> 
> ```
> set-style(bezier: (stroke: (dash: "dashed")))
> bezier((0,0), (5,0), (1,2), (4,-2))
> ```
> 
> Can you give a more detailed example where it does not? Did you call `set-style` before in the canvas?

in fact, neither does the following:
```typst
#cetz.canvas({
  import cetz.draw: *
  merge-path({
    bezier(
      (1.5, -5),
      (3.5, -6),
      (1.5, -6.5),
      stroke: (dash: "dashed", thickness: 1pt),
    )
    bezier((7, -5), (9, -6), (9, -4.5))
  })
})
```

**Comment by johannes-wolf** [comment]
For `merge-path` you have to set it for the new, merged path via `merge-path`'s `stroke:` attribute. You cannot set different stroke or fill styles for different merged parts.

`merge-path`'s `stroke` cannot be set via `set-style` (which is a bug I guess).
