### ISSUE TITLE
Add delta angle to arc

### ISSUE THREAD

**Issue by fenjalien** [johannes-wolf/typst-canvas#59]
Currently you can only define the start and end angles of an arc. It should also be possible to set the delta angle along with either a start and end angle.

Syntax could be something along the lines of:
```
arc((0,0), start: 10deg, delta: 30deg)
// or equivalently
arc((0,0), end: 40deg, delta: 30deg)
```

**Comment by lecarrera-tec** [comment]
@johannes-wolf  I could implement this, if you allowed me.

**Comment by johannes-wolf** [comment]
> @johannes-wolf I could implement this, if you allowed me.

Yes, of course :)
