### ISSUE TITLE
Add a `mark` dictionary variable to the context for the arrows

### ISSUE THREAD

**Issue by lecarrera-tec** [johannes-wolf/typst-canvas#62]
The default at the canvas creation:
mark(start: none, end: none, size: 0.15, stroke: black, fill: black)

One or more of the options could be updated at any time.

When drawing a line, an arc or a bezier (the grid also?), it will look at mark.start or mark.end. If setted, it will draw the mark accordingly.

The option will be added to each of the elements as auto (use the global mark) or specific. From the line command, the mark-* options will be removed.

**Comment by fenjalien** [comment]
Do my changes to #60 help resolve this?

**Comment by lecarrera-tec** [comment]
I think this is complementary.

**Comment by fenjalien** [comment]
This can be closed now as #60 has been merged
