### ISSUE TITLE
Feature request, yielding many nodes from content

### ISSUE THREAD

**Issue by astrale-sharp** [johannes-wolf/typst-canvas#70]
The idea would be to do something like this:
```lisp
#import "../../canvas.typ": *

#box(stroke: 2pt + red, canvas({
    import "../../draw.typ": * 
    content([ #content_node("lab1")[This] is #content_node("lab2")[Sparta]  ]),
    line("lab1", "lab2") 
}))
```

where there would be a line drawn from `This` to `Sparta`
tikz has support for something like this, and it would help a lot cause doing this by hand is very annoying/not reliable

I'm looking at the code trying to see how feasible it would be.

with maybe `cn` or `node` or `cnode` as an alias or replacement for content_node

**Comment by astrale-sharp** [comment]
reading the source code, it feels like something in the line of this

`content((0,0), [#content((), [This ], name : "lab1") is #content((), name: "lab2", [sparta])!])` might yield something similar to what is wanted (given how `process-element` is recursive

infortunatly, it gives this instead : 
![image](https://github.com/johannes-wolf/typst-canvas/assets/53686698/383e9826-a847-4fca-b61c-cc2dc091451a)

On to investigate!

**Comment by astrale-sharp** [comment]
Being able to get the previous coordinate as anchor would be useful to impl this with a dedicated syntax
something like "previous.end" possible for a coordinate

**Comment by fenjalien** [comment]
I don't see what you're objective is, can you show us an example of your desired output? Could you also find the relevant tikz documentation?

**Comment by astrale-sharp** [comment]
example of tikz code with result : 
```latex
\documentclass[border=3.141592]{standalone}
\usepackage{tikz}
\usetikzlibrary{arrows.meta,
                positioning,
                tikzmark}

\begin{document}
\begin{tikzpicture}[remember picture,
    node distance = 7mm and 1mm,
every node/.style = {inner sep=2pt, font=\sffamily},
every edge/.style = {draw, line width=1pt,-Straight Barb}
                        ]
\node (A) {The \subnode{s1}{quick} brown fox \subnode{s2}{jumps} over the \subnode{s3}{lazy} dog};
\node (a) [below left=of A]     {quick};
\node (b) [below=of s2]          {jumps};
\node (c) [below right=of A]    {lazy};
\draw[->]   (s1) edge (a)   (s2) edge (b)   (s3) edge (c);
\end{tikzpicture}
\end{document}
```
![image](https://github.com/johannes-wolf/typst-canvas/assets/53686698/214835ab-08c6-4bec-9804-810a57d8ff0b)

**Comment by astrale-sharp** [comment]
tikzmarknode is how I usually see it in tho : 

tikz docs from page 5 of [this manual](https://ctan.math.washington.edu/tex-archive/graphics/pgf/contrib/tikzmark/tikzmark.pdf)
```
\tikzmarknode[〈options〉]{〈name〉}{〈contents〉}
This is a reincarnation of the original \tikzmark command which places its
contents inside a \tikz node. It also defines a tikzmark with the same name.
Using a sneaky trick with \mathchoice, it works inside a math environment.
The spacing either side might not be quite right as although it detects the
math style it doesn’t got beyond that. The options are passed to the node.
Two styles are attempted, one on the surrounding picture and one on the
node, which are:
• every tikzmarknode picture
• every tikzmarknode
To refer to the node, use usual TikZ coordinates. To refer to the underlying
tikzmark, use the special tikzmark coordinates (see below).
```

with an example: 
![image](https://github.com/johannes-wolf/typst-canvas/assets/53686698/5e6aa11e-32ba-491a-ad56-6e58e79aa665)

**Comment by astrale-sharp** [comment]
My current investigation of a simple solution to implement this would be to try to generate something like this from a new function 
```
#box(stroke: 2pt + red, inset: 5pt, canvas(
    // debug: true,
    {
    import "../../draw.typ": * 
    content((), name : "lab1")[This ]
    content("lab1.right", name : "tmp" )[#h(0.6em) is]    
    content("tmp.right", name : "lab1")[#h(0.6em) Sparta #h(0.6em)]    
}))
```
Unfortunatly doing this doesn't retain the space between contents information and even trying to hack it back with h(...) doesn't work, I don't really now why : 
![image](https://github.com/johannes-wolf/typst-canvas/assets/53686698/7630a864-0fbf-4736-8904-44a77ef306de)

**Comment by johannes-wolf** [comment]
The `content` is placed centered by default, so you have to set the anchor like this:
```
content("lab1.right", name: "tmp", anchor: "left")[is]    
content("tmp.right", name: "lab1", anchor: "left")[Sparta]    
```

**Comment by johannes-wolf** [comment]
The tikz example can be achieved using the following:
```
    fill(black)
    content-padding(.1)

    content((), [The quick brown fox jumps over the lazy dog], name: "b")

    content((rel: (0, -1), to: "b.left"), [quick], anchor: "right", name: "q")
    line((rel: (-3, -.1), to: "b.below"), "q.top", mark-end: ">")

    content((rel: (0, -1), to: "b.center"), [jumps], name: "j")
    line((rel: (0, -.1), to: "b.below"), "j.top", mark-end: ">")

    content((rel: (0, -1), to: "b.right"), [lazy], anchor: "left", name: "l")
    line((rel: (3, -.1), to: "b.below"), "l.top", mark-end: ">")
```

Which outputs:
![grafik](https://github.com/johannes-wolf/typst-canvas/assets/519002/603a7e98-2b64-48f5-b771-a6ef5b6cf1a9)

**Comment by astrale-sharp** [comment]
Following your advice we still lose space information

```
    content((), name : "lab1", anchor: "left")[This]
    content("lab1.right", name : "tmp", anchor: "left" )[ is ]    
    content("tmp.right", name : "lab1", anchor: "left")[Sparta]    
```

![image](https://github.com/johannes-wolf/typst-canvas/assets/53686698/a20da450-3258-48c0-bb1c-db3b3a58ae84)

I have two solutions (hacks?) that come in mind.

Consider the following content `[The quick brown fox jumps]`,
if we want all of the words to be nodes we can write either code re inputting the spaces :

```
#let space = h(0.25em)
#box(stroke: 2pt + red, inset: 5pt, canvas(
    // debug: true,
    {
    import "../../draw.typ": * 
    content((), name : "one", anchor: "left")[The#space]
    content("one.right", name : "two", anchor: "left" )[brown#space]
    content("two.right", name : "three", anchor: "left")[fox #space]
    content("three.right", name : "four", anchor: "left")[jumps]
    line("two", (1,1), stroke : 1pt + red)
    line((1,1), "three", stroke : 1pt + red)
}))```
![image](https://github.com/johannes-wolf/typst-canvas/assets/53686698/e2add9bf-7df5-48cd-a982-dc66683cbcd4)

**Comment by astrale-sharp** [comment]
but I'd be afraid breakline information would be lost, that's why we could also try this:
```
#let space = h(0.25em)

#box(stroke: 2pt + red, inset: 5pt, canvas(
    // debug: true,
    {
    import "../../draw.typ": * 
    content((), name : "main", anchor: "left")[The brown fox jumps] // this is to ensure rendering is done well
    
    content((), name : "the", anchor: "left")[#hide[The #space]]
    content("the.right", name : "brown", anchor: "left")[#hide[brown]]

    content("main.left", name : "the_brown_hidden", anchor: "left" )[#hide[The brown #space]]
    content("the_brown_hidden.right", name : "fox", anchor: "left")[#hide[fox]]

    content("main.left", name : "the_brown_fox_hidden", anchor: "left" )[#hide[The brown fox#space]]
    content("the_brown_fox_hidden.right", name : "jumps", anchor: "left")[#hide[jumps]]

    line("the", (1,1), stroke : 1pt + red)
    line((1,1), "fox", stroke : 1pt + red)
}))
```
![image](https://github.com/johannes-wolf/typst-canvas/assets/53686698/24936859-a6df-4ac7-be9a-c787d921de85)

the breakline and space would be globally retained but some nodes might be misplaced (placed on the right when the line should have been broken instead)
that could be generated from this code (new syntax proposed):
```
contents( 
        [The ],
        node(name : "brown")[brown ], // only this name will be recorded
        [fox ],
        [jumps.]
)
```

**Comment by astrale-sharp** [comment]
but maybe this should be done in a different more stateful way where you call
 `content(...)[The #make_node(name : "brown")[brown] fox jumps]` 
where make_node would write the position of brown into a state, I think this would be the simplest way but I'm not sure this is very compatible with this library

**Comment by johannes-wolf** [comment]
Have you considered trying a callback based approach? Making `content` call its argument if it is a function would enable returning additional information maybe by using a (global) state object? As typst does not allow writing to variables outsides a function I can see no other option than using sates or parsing.

**Comment by johannes-wolf** [comment]
@astrale-sharp With #89 I have added a hack that allows measuring parts of a content call.
I think typsts API is to limited atm. to correctly support this feature.

You can test my hack with the following code:
```
//#import "@local/canvas:0.0.1": canvas, canvas-draw
#import "lib.typ": *

#let data = (0, (1, 5, (3, 2, 3, 3, 4), 2))

#box(stroke: 2pt + red, inset: 5pt, canvas({
  import draw: *

  content((0,0), [This],(content: [ is], name: "is"),[ Sparta!],
          name: "text")

  line((0, -3), "text.is", mark: (end: ">"))
}))

```

**Comment by astrale-sharp** [comment]
Exciting! We'll get to there all the way, I really would love this feature (but I'm working on other projects right now ;))

**Comment by johannes-wolf** [comment]
I am closing this, as I see no (good) option to implement this as of now.

**Comment by astrale-sharp** [comment]
Fair enough, if I get more time I'll try to come up with something, but I'd probably wait for rendering features to be easier to use (laurenz said it was going to be a thing)
