### ISSUE TITLE
Start using semver / Submit package

### ISSUE THREAD

**Issue by fenjalien** [johannes-wolf/typst-canvas#72]
Given Typst has started taking package submissions we should obviously submit this one!

- [x] Add a `typst.toml`
- [x] Sort out versioning
  - I would advise we start at `0.0.1` and only increase maintanence number (e.g. `0.0.2`) until we are happy that this package is "stable" and won't make any more drastic changes.
- [ ] Create a github actions release workflow
  - This should only keep what is related to the running of the package (e.g. no manual or tests)

I'm not sure *when* we should release a new version, easiest would be on every PR merge...

**Comment by johannes-wolf** [comment]
There is the question how the `#import "typst-canvas/draw.typ": *` can be realized with the package manager.

One option would be having an additional typst file that imports `canvas.typ` and `draw.typ`.
Downside is, that one has to use all commands with a namespace.

**Comment by fenjalien** [comment]
Hmm could point, that might be one for the questions channel in the discord server...

**Comment by fenjalien** [comment]
Okay it shouldn't be a problem if we do it like this:
`lib.typ`:
```
#import "canvas.typ": canvas
#import "draw.typ": *
#import "vector.typ"
#import "matrix.typ"
```
`main.typ`:
```
#import "@local/typst-canvas:0.0.1": canvas

#canvas({
  import "@local/typst-canvas:0.0.1": *
})
```

**Comment by johannes-wolf** [comment]
The PR #73 uses the following approach:
```
#import "@local/canvas:0.0.1"

#canvas.canvas({
  import canvas.draw: *
  // ...
})
```

**Comment by N3xed** [comment]
Just for some inspiration, I use it like this:

```
#canvas({
    import canvas-draw: *
})
```

so `lib.typ` would be e.g.:
```
#import "canvas.typ": canvas
#let canvas-draw = (() => {
    import "draw.typ"
    return draw
})()
```

But maybe they'll add support for arbitrary properties on functions for non-builtin functions, then `draw` could be a property on the `canvas` function (which would be nice).

**Comment by johannes-wolf** [comment]
@N3xed I would like to stick to the `import canvas.draw` version. You can then write:
```
#import '@local/canvas:0.0.1': canvas, draw
#canvas({
  import draw: *
  // ...
})
```

**Comment by N3xed** [comment]
My only concern with that is, that `draw` is a really common function name. And with your approach `draw` would be a globally available module that is only used to import the actual draw functions. I guess what I'm trying to say is, that I think it doesn't really fit the name.

But then again, name conflicts can be worked around with my solution.

**Comment by johannes-wolf** [comment]
You are right, I did not really think about namespace collisions. I think I will add your approach :+1:.

**Comment by schang412** [comment]
Hi,

I am working on updating https://github.com/fenjalien/circuitypst and it currently uses `vector.typ` and `coordinate.typ`.

I am still relatively new to typst syntax, so please correct me if not necessary. However, could lib.typ also export the above files for usage?
```diff
diff --git a/lib.typ b/lib.typ
index 337f7a4..3732730 100644
--- a/lib.typ
+++ b/lib.typ
@@ -1,5 +1,7 @@
 #import "canvas.typ": canvas
 #import "draw.typ"
+#import "vector.typ"
+#import "coordinate.typ"

 // This is an alias to prevent name collisions
 // You can use it for importing the module into the
```

Thanks.

**Comment by johannes-wolf** [comment]
> Hi,
> 
> I am working on updating https://github.com/fenjalien/circuitypst and it currently uses `vector.typ` and `coordinate.typ`.
> 
> I am still relatively new to typst syntax, so please correct me if not necessary. However, could lib.typ also export the above files for usage?
> 
> ```diff
> diff --git a/lib.typ b/lib.typ
> index 337f7a4..3732730 100644
> --- a/lib.typ
> +++ b/lib.typ
> @@ -1,5 +1,7 @@
>  #import "canvas.typ": canvas
>  #import "draw.typ"
> +#import "vector.typ"
> +#import "coordinate.typ"
> 
>  // This is an alias to prevent name collisions
>  // You can use it for importing the module into the
> ```
> 
> Thanks.

Added. Thanks for the hint.

**Comment by johannes-wolf** [comment]
Closing this as it is resolved. Release packages can be generated using `just package <output-dir>`.
