### ISSUE TITLE
coordinate error strict mode 

### ISSUE THREAD

**Issue by astrale-sharp** [johannes-wolf/typst-canvas#91]
Hey,

Wouldn't it be nice if when your coordinate is "name.topleft" or ""name.top.left" or if name is undefined you get an error with `a list of what anchors are valid` or `what named element are available`? :innocent:

**Comment by astrale-sharp** [comment]
tested with 0.0.1 since my computer is small and typst cant just bring the repo in for me (yet?)

**Comment by fenjalien** [comment]
I don't undstand your question or request? When a name or anchor is not recognised CeTZ prints a list of existing ones in the error message.

```typst
circle((), name: "circle")
circle("circle.other")
```
![image](https://github.com/johannes-wolf/typst-canvas/assets/34489450/a1eff626-7a70-4e64-b397-1d2c41a6a87b)

**Comment by johannes-wolf** [comment]
Tested it with the online Editor. It seems that assertions from packages are ignored there, while they work with local packages. Maybe this is a typst bug?

Test:
https://typst.app/project/rzySqn8YqS4A_uZ46yhvZO

Local package:
![grafik](https://github.com/johannes-wolf/typst-canvas/assets/519002/4cc4cd95-a5ba-420b-8b88-1bf9ae7c91ef)

**Comment by astrale-sharp** [comment]
Oh fair enough, yes i tested it on the online editor! it just appear to succeed for all these cases! I'll open an issue in typst later

**Comment by ThatOneCalculator** [comment]
> Tested it with the online Editor. It seems that assertions from packages are ignored there, while they work with local packages. Maybe this is a typst bug?

Can I ask how you were able to get CeZT working on typst.app?

**Comment by johannes-wolf** [comment]
With the current version of Typst, assertions are shown in the online editor:
```typst
#import "@preview/cetz:0.1.2": canvas, plot, draw
#set page(width: auto, height: auto)

#canvas(length: 1cm, {
  import draw: *
  circle("non-existing")
})
```

![grafik](https://github.com/johannes-wolf/cetz/assets/519002/9f70b6f9-498b-4d86-b791-cd62254fc610)

**Comment by ThatOneCalculator** [comment]
Oh nice! Does this mean that everything's compatible, or are there parts still missing? I'm still very new to Typst (started a couple days ago) but I pasted an example at the end of a document I'm working on and it seems to work like a charm!

![image](https://github.com/johannes-wolf/cetz/assets/44733677/7c5a7232-5a3b-4382-a8b6-637501ab8f02)
