### ISSUE TITLE
Cannot use em units in length while using content

### ISSUE THREAD

**Issue by dipamsen** [johannes-wolf/typst-canvas#99]
`length: 2em` is not allowed if content is used in the sketch.

MRE:

```ts
#import "@preview/cetz:0.0.1"

#cetz.canvas(length: 3em, {
  import cetz.draw: *

  circle((0, 0), radius: 1)
  content((), [Hello])
})
```

Error:

![image](https://github.com/johannes-wolf/typst-canvas/assets/59444569/68417413-b3a5-43cf-a5bb-8495db8827fa)

**Comment by fenjalien** [comment]
thanks for the bug! 

Yea can't divide by `em`, @johannes-wolf would it be easiest to make sure `length` is converted to `pt` at the start of `canvas`?

**Comment by johannes-wolf** [comment]
Yes I opened a PR.
